[tool.poetry]
name = "streamlit-app2"
version = "0.1.0"
description = ""
authors = ["pajtas11 pajtas11@gmail.com"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.35.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
